version: '3'
services:
    #PHP Service
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: demo_cms_php:latest
        container_name: php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/storage
        networks:
            - app-network
    #Nginx Service
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: demo_cms_nginx:latest
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
