version: '3'
services:
    #PHP Service
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: app:lastest
        container_name: php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "3000:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
