version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - cp -rf .env.example .env
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 193107375733.dkr.ecr.ap-southeast-1.amazonaws.com
      - docker-compose -p demo_cms -f docker-compose.yml build php
      - docker tag demo_cms_php:latest 193107375733.dkr.ecr.ap-southeast-1.amazonaws.com/demo_cms_php:latest
      - docker-compose -p demo_cms -f docker-compose.yml build nginx
      - docker tag demo_cms_nginx:latest 193107375733.dkr.ecr.ap-southeast-1.amazonaws.com/demo_cms_nginx:latest
  post_build:
    commands:
      - docker push 193107375733.dkr.ecr.ap-southeast-1.amazonaws.com/demo_cms_php:latest
      - docker push 193107375733.dkr.ecr.ap-southeast-1.amazonaws.com/demo_cms_nginx:latest
artifacts:
  files:
    - '**/*'
    - '.env'
